In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("data.csv")
df

,Unnamed: 0,text,time,source,link
0,0,üá∫üá∏üí∏ –ü–ª–∞–Ω –ë–∞–π–¥–µ–Ω–∞ –Ω–∞ 80 –º–∏–ª–ª–∏–∞—Ä–¥–æ–≤ –¥–æ–ª–ª–∞—Ä–æ–≤ –ø–æ ...,"2021-05-05, 15:38:30",Telegram,https://t.me/Full_Time_Trading
1,1,üåéüá®üá≥ G7: –ö–ò–¢–ê–ô –ü–†–ï–°–õ–ï–î–£–ï–¢ –£–ô–ì–£–†–û–í –ò –î–†–£–ì–ò–ï –ú–ï–ù–¨...,"2021-05-05, 15:31:38",Telegram,https://t.me/Full_Time_Trading
2,2,"üíÅ‚Äç‚ôÄÔ∏è ZOOM $ZM –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ò–°–°–õ–ï–î–£–ï–¢ –ü–†–û–ë–õ–ï–ú–´...","2021-05-05, 15:30:44",Telegram,https://t.me/Full_Time_Trading
3,3,"üó£ –¢–†–ê–ú–ü:\n\n–¢–û, –ß–¢–û –°–î–ï–õ–ê–õ–ò FACEBOOK $FB, TWIT...","2021-05-05, 15:29:55",Telegram,https://t.me/Full_Time_Trading
4,4,üá∫üá∏ü¶† CDC –ø—Ä–æ–≥–Ω–æ–∑–∏—Ä—É–µ—Ç –≤—Å–ø–ª–µ—Å–∫ —Å–ª—É—á–∞–µ–≤ –∑–∞–±–æ–ª–µ–≤–∞–Ω...,"2021-05-05, 15:24:14",Telegram,https://t.me/Full_Time_Trading
...,...,...,...,...,...
995,995,‚ùóÔ∏èüá∑üá∫–†–æ—Å—Å–∏—è –≤–≤–µ–ª–∞ –æ—Ç–≤–µ—Ç–Ω—ã–µ —Å–∞–Ω–∫—Ü–∏–∏ –ø—Ä–æ—Ç–∏–≤ 8 –ø—Ä–µ...,"2021-04-30, 15:08:02",Telegram,https://t.me/Full_Time_Trading
996,996,‚ùóÔ∏èüá∑üá∫30 –ê–ü–†–ï–õ–Ø - –ü–û–°–õ–ï–î–ù–ò–ô –î–ï–ù–¨ –î–ï–ö–õ–ê–†–ê–¶–ò–û–ù–ù–û–ô ...,"2021-04-30, 15:06:16",Telegram,https://t.me/Full_Time_Trading
997,997,üî• Southwest Airlines $LUV –≤–µ—Ä–Ω—ë—Ç—Å—è –≤ –ö–æ—Å—Ç–∞-–†–∏–∫...,"2021-04-30, 15:06:01",Telegram,https://t.me/Full_Time_Trading
998,998,üí™ –ì–µ–Ω–µ—Ä–∞–ª—å–Ω—ã–π –¥–∏—Ä–µ–∫—Ç–æ—Ä Chevron $CVX: –î–∏–≤–∏–¥–µ–Ω–¥—ã...,"2021-04-30, 15:05:31",Telegram,https://t.me/Full_Time_Trading
999,999,"üá∫üá∏ USTR –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ü–†–ò–û–†–ò–¢–ï–¢–ù–´–ô –°–ü–ò–°–û–ö –ù–ê–ë–õ...","2021-04-30, 15:02:42",Telegram,https://t.me/Full_Time_Trading

In [5]:
df = df.drop(["Unnamed: 0", "time", "link", "source"], axis=1)

In [6]:
df

                                                  text
0    üá∫üá∏üí∏ –ü–ª–∞–Ω –ë–∞–π–¥–µ–Ω–∞ –Ω–∞ 80 –º–∏–ª–ª–∏–∞—Ä–¥–æ–≤ –¥–æ–ª–ª–∞—Ä–æ–≤ –ø–æ ...
1    üåéüá®üá≥ G7: –ö–ò–¢–ê–ô –ü–†–ï–°–õ–ï–î–£–ï–¢ –£–ô–ì–£–†–û–í –ò –î–†–£–ì–ò–ï –ú–ï–ù–¨...
2    üíÅ‚Äç‚ôÄÔ∏è ZOOM $ZM –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ò–°–°–õ–ï–î–£–ï–¢ –ü–†–û–ë–õ–ï–ú–´...
3    üó£ –¢–†–ê–ú–ü:\n\n–¢–û, –ß–¢–û –°–î–ï–õ–ê–õ–ò FACEBOOK $FB, TWIT...
4    üá∫üá∏ü¶† CDC –ø—Ä–æ–≥–Ω–æ–∑–∏—Ä—É–µ—Ç –≤—Å–ø–ª–µ—Å–∫ —Å–ª—É—á–∞–µ–≤ –∑–∞–±–æ–ª–µ–≤–∞–Ω...
..                                                 ...
995  ‚ùóÔ∏èüá∑üá∫–†–æ—Å—Å–∏—è –≤–≤–µ–ª–∞ –æ—Ç–≤–µ—Ç–Ω—ã–µ —Å–∞–Ω–∫—Ü–∏–∏ –ø—Ä–æ—Ç–∏–≤ 8 –ø—Ä–µ...
996  ‚ùóÔ∏èüá∑üá∫30 –ê–ü–†–ï–õ–Ø - –ü–û–°–õ–ï–î–ù–ò–ô –î–ï–ù–¨ –î–ï–ö–õ–ê–†–ê–¶–ò–û–ù–ù–û–ô ...
997  üî• Southwest Airlines $LUV –≤–µ—Ä–Ω—ë—Ç—Å—è –≤ –ö–æ—Å—Ç–∞-–†–∏–∫...
998  üí™ –ì–µ–Ω–µ—Ä–∞–ª—å–Ω—ã–π –¥–∏—Ä–µ–∫—Ç–æ—Ä Chevron $CVX: –î–∏–≤–∏–¥–µ–Ω–¥—ã...
999  üá∫üá∏ USTR –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ü–†–ò–û–†–ò–¢–ï–¢–ù–´–ô –°–ü–ò–°–û–ö –ù–ê–ë–õ...

[1000 rows x 1 columns]

In [9]:
df["target"] = np.nan
df

                                                  text  target
0    üá∫üá∏üí∏ –ü–ª–∞–Ω –ë–∞–π–¥–µ–Ω–∞ –Ω–∞ 80 –º–∏–ª–ª–∏–∞—Ä–¥–æ–≤ –¥–æ–ª–ª–∞—Ä–æ–≤ –ø–æ ...     NaN
1    üåéüá®üá≥ G7: –ö–ò–¢–ê–ô –ü–†–ï–°–õ–ï–î–£–ï–¢ –£–ô–ì–£–†–û–í –ò –î–†–£–ì–ò–ï –ú–ï–ù–¨...     NaN
2    üíÅ‚Äç‚ôÄÔ∏è ZOOM $ZM –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ò–°–°–õ–ï–î–£–ï–¢ –ü–†–û–ë–õ–ï–ú–´...     NaN
3    üó£ –¢–†–ê–ú–ü:\n\n–¢–û, –ß–¢–û –°–î–ï–õ–ê–õ–ò FACEBOOK $FB, TWIT...     NaN
4    üá∫üá∏ü¶† CDC –ø—Ä–æ–≥–Ω–æ–∑–∏—Ä—É–µ—Ç –≤—Å–ø–ª–µ—Å–∫ —Å–ª—É—á–∞–µ–≤ –∑–∞–±–æ–ª–µ–≤–∞–Ω...     NaN
..                                                 ...     ...
995  ‚ùóÔ∏èüá∑üá∫–†–æ—Å—Å–∏—è –≤–≤–µ–ª–∞ –æ—Ç–≤–µ—Ç–Ω—ã–µ —Å–∞–Ω–∫—Ü–∏–∏ –ø—Ä–æ—Ç–∏–≤ 8 –ø—Ä–µ...     NaN
996  ‚ùóÔ∏èüá∑üá∫30 –ê–ü–†–ï–õ–Ø - –ü–û–°–õ–ï–î–ù–ò–ô –î–ï–ù–¨ –î–ï–ö–õ–ê–†–ê–¶–ò–û–ù–ù–û–ô ...     NaN
997  üî• Southwest Airlines $LUV –≤–µ—Ä–Ω—ë—Ç—Å—è –≤ –ö–æ—Å—Ç–∞-–†–∏–∫...     NaN
998  üí™ –ì–µ–Ω–µ—Ä–∞–ª—å–Ω—ã–π –¥–∏—Ä–µ–∫—Ç–æ—Ä Chevron $CVX: –î–∏–≤–∏–¥–µ–Ω–¥—ã...     NaN
999  üá∫üá∏ USTR –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ü–†–ò–û–†–ò–¢–ï–¢–ù–´–ô –°–ü–ò–°–û–ö –ù–ê–ë–õ...     NaN

[1000 rows x 2 columns]

In [20]:
df['text'].isnull().sum()

3

In [21]:
df["target"] = df.apply(lambda row : 0 if pd.notnull(row["text"]) and row["text"].find("$") != -1 else np.nan, axis=1)
df

                                                  text  target
0    üá∫üá∏üí∏ –ü–ª–∞–Ω –ë–∞–π–¥–µ–Ω–∞ –Ω–∞ 80 –º–∏–ª–ª–∏–∞—Ä–¥–æ–≤ –¥–æ–ª–ª–∞—Ä–æ–≤ –ø–æ ...     NaN
1    üåéüá®üá≥ G7: –ö–ò–¢–ê–ô –ü–†–ï–°–õ–ï–î–£–ï–¢ –£–ô–ì–£–†–û–í –ò –î–†–£–ì–ò–ï –ú–ï–ù–¨...     NaN
2    üíÅ‚Äç‚ôÄÔ∏è ZOOM $ZM –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ò–°–°–õ–ï–î–£–ï–¢ –ü–†–û–ë–õ–ï–ú–´...     0.0
3    üó£ –¢–†–ê–ú–ü:\n\n–¢–û, –ß–¢–û –°–î–ï–õ–ê–õ–ò FACEBOOK $FB, TWIT...     0.0
4    üá∫üá∏ü¶† CDC –ø—Ä–æ–≥–Ω–æ–∑–∏—Ä—É–µ—Ç –≤—Å–ø–ª–µ—Å–∫ —Å–ª—É—á–∞–µ–≤ –∑–∞–±–æ–ª–µ–≤–∞–Ω...     NaN
..                                                 ...     ...
995  ‚ùóÔ∏èüá∑üá∫–†–æ—Å—Å–∏—è –≤–≤–µ–ª–∞ –æ—Ç–≤–µ—Ç–Ω—ã–µ —Å–∞–Ω–∫—Ü–∏–∏ –ø—Ä–æ—Ç–∏–≤ 8 –ø—Ä–µ...     NaN
996  ‚ùóÔ∏èüá∑üá∫30 –ê–ü–†–ï–õ–Ø - –ü–û–°–õ–ï–î–ù–ò–ô –î–ï–ù–¨ –î–ï–ö–õ–ê–†–ê–¶–ò–û–ù–ù–û–ô ...     NaN
997  üî• Southwest Airlines $LUV –≤–µ—Ä–Ω—ë—Ç—Å—è –≤ –ö–æ—Å—Ç–∞-–†–∏–∫...     0.0
998  üí™ –ì–µ–Ω–µ—Ä–∞–ª—å–Ω—ã–π –¥–∏—Ä–µ–∫—Ç–æ—Ä Chevron $CVX: –î–∏–≤–∏–¥–µ–Ω–¥—ã...     0.0
999  üá∫üá∏ USTR –°–û–û–ë–©–ê–ï–¢, –ß–¢–û –ü–†–ò–û–†–ò–¢–ï–¢–ù–´–ô –°–ü–ò–°–û–ö –ù–ê–ë–õ...     NaN

[1000 rows x 2 columns]

In [22]:
df.to_csv("data.csv")